version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: docker-frontend
    command: serve -s build -l 3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - ed-docker

  api:
    container_name: ed-api
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db  
    networks:
      - ed-docker

  api_db:
    container_name: ed-db
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
    networks:
      - ed-docker

  auth:
    build: ./auth
    container_name: ed-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://ed-auth
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - ed-docker
  
  auth_db:
    image: mongo:latest
    container_name: ed-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - ed-docker

  nginx:
    image: nginx:stable-alpine      
    container_name: ed-nginx
    ports:
      - "80:80"
    volumes: 
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:         
      - frontend
      - api
      - auth
    networks:
      - ed-docker

volumes:
    mongodb_api:
    mongodb_auth:

networks: 
  ed-docker:
    driver: bridge
